title: "FB-Tagung 2025"
theme: just-the-docs

# Navigation (Seitenstruktur)
nav:
  - title: Startseite
    url: /
  - title: Gesamtübersicht
    url: /gesamtuebersicht
  - title: Workshops
    children:
      - title: Workshop 1
        url: /workshop1
      - title: Workshop 2
        url: /workshop2
  - title: Panels
    children:
      - title: Panel 1
        url: /panel1
  - title: Materialien
    url: /materialien
