title: "FB-Tagung 2025"
theme: just-the-docs

# Navigation (Seitenstruktur)
nav:
  - title: Startseite
    url: /
  - title: Gesamtpräsentation
    url: /gesamtpräsentation.md
  - title: Workshops
    children:
      - title: Belastbarkeit & Beziehungsarbeit
        url: /Workshops/Belastbarkeit & Beziehungsarbeit.md
      - title: Erfahrungsaustausch Fans & Polizei
        url: /Workshops/Erfahrungsaustausch Fans & Polizei.md
     - title: Fanarbeit unter Druck - Konsequenzen des Karlsruher Urteils
        url: /Workshops/Fanarbeit unter Druck - Konsequenzen des Karlsruher Urteils.md
    - title: Fankulturelle Entwicklungen
      url: /Workshops/Fankulturelle Entwicklungen.md
        - title: Frauenbundesliga
        url: /Workshops/Frauenbundesliga.md
      - tilte: Jugndfanarbeit
      url: /Workshops/Jugendfanarbeit.md
        - title: Lasst uns mal drüber reden! 2 Jahre FB D&I
        url: /Workshops/Lasst uns mal drüber reden! 2 Jahre FB D&I.md
        - title: Vorbereitet sein für kritische und schwierige Situationen
        url: /Workshops/Vorbereitet sein für kritische und schwierige Situationen.md
        - title: Zukunft FZM
        url: /Workshops/Zukunft FZM.md
  - title: Panels
    children:
      - title: Awareness-Konzepte und Anlaufstellen für sexualisierte Gewalt
        url: /Panels/Awareness-Konzepte und Anlaufstellen für sexualisierte Gewalt.md
      - title: Inklusive Kommunikationsangebote für Fans mit Hörbehinderung
        url: /Panels/Inklusive Kommunikationsangebote für Fans mit Hörbehinderung.md
       - title: Kenntnisse und Einfluss
        url: /Panels/Kenntnisse und Einfluss.md
      - title: Terminierung der Spieltage + Reiseweg-Thematik
        url: /Panels/Terminierung der Spieltage + Reiseweg-Thematik.md
      - title: Umgang mit Pyrotechnik in der Fanarbeit
        url: /Panels/Umgang mit Pyrotechnik in der Fanarbeit.md
